# Generated by Django 3.2.25 on 2025-02-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': [('can_view', 'Can View Document'), ('can_create', 'Can Create Document'), ('can_edit', 'Can Edit Document'), ('can_delete', 'Can Delete Document')],
            },
        ),
    ]
